# SEE AN EXAMPLE AT https://github.com/MinecraftForge/MinecraftForge/blob/1.13.x/mods.toml

# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[2.0,)"

[[mods]]
    modId="tricksters"
    version="0.0.1-beta"
    displayName="Tricksters"
    # multi line!
    description='''Made for SpookyJam 2019 by skyjay1, with help from TheOneTraveler'''
    [[dependencies.tricksters]]
        modId="forge"
        mandatory=true
        versionRange="[28,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.tricksters]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.14.3,]"
        ordering="NONE"
        side="BOTH"